#!/bin/bash

prob_param=$1
dir_name=""

if [ "$prob_param" == "" ]; then
echo 'problem name is missing'
echo 'please write custom problem name or [next] to auto generate one'
exit $?
fi

if [ "$prob_param" == "next" ]; then
  last_dir=`ls |grep 'problem_' | tail -n 1 | cut -d '_' -f 2`
  dir_name="problem_$[$last_dir+1]"
else
  dir_name=$prob_param
fi

mkdir $dir_name



prob_dir_structure()
{
  echo $dir_name

  mkdir "$dir_name/lib"
  touch "$dir_name/.description"
  git checkout -b "${dir_name}"
}


prob_dir_structure

exit $?
